### PR TITLE
Attempt to fix #170 Mismatched gcp and AWS links

### LINKED ISSUE #170: [BUG] Mismatched gcp and AWS links
**Describe the bug**

`pysradb metadata` mixes up the AWS/SRA/GCP links

**To Reproduce**

```pysradb metadata --detailed SRP288365```

### PR DESCRIPTION
**Pull request by cksajil**
On branch sajil-develop
 Changes to be committed:
	modified:   pysradb/sraweb.py
	modified:   pysradb/utils.py
	modified:   tests/test_utils.py

### CODE REVIEW

**Comment by saketkc** [comment]
Thanks, though this appears to completely wipes out the AWS and GCP links which is not what we want (also it fails with `pysradb metadata --detailed SRP288365`)

**Comment by cksajil** [comment]
@saketkc can I place the AWS and GCP links in new columns or do you want to place those is any of the existing columns?

**Comment by saketkc** [comment]
Putting them into new column(s) should be fine.

**Comment by cksajil** [comment]
@saketkc I added the links to new columns. Let me know if this is fine.

**Comment by saketkc** [comment]
Thanks @cksajil for helping with this! I have added some comments on the PR that would be good to address before we can merge this.

**Comment by saketkc** [comment]
Hi @cksajil, with PR #177, I believe the original issue has been addressed. Thanks once again for helping with the fix.

**Pull request closed without merging**
