### PR TITLE
Add a check for kwargs

### LINKED ISSUE #29: keyerror while checking for a key in kwargs
### What I Did
```
sc=SRAweb()
sc.gse_to_gsm("GSE34438") #no keyword arguments
```
```
Traceback (most recent call last):
  File "test_sraweb.py", line 151, in <module>
    sc.gse_to_gsm("GSE34438")
  File "/home/dibya/Documents/new_pysradb/pysradb/pysradb/sraweb.py", line 536, in gse_to_gsm
    if kwargs["detailed"] == True:
KeyError: 'detailed'

```

### PR DESCRIPTION
**Pull request by dibyaaaaax**
fixes #29

### CODE REVIEW

**Comment by saketkc** [comment]
Thanks @dibyaaaaax! I will wait till we have merged #23 so that we can ideally also incorporate more test cases for this.

**Comment by saketkc** [comment]
Hi @dibyaaaaax, this should be ready to merge. Would you have time to add a few test cases for this?

**Comment by dibyaaaaax** [comment]
@saketkc sure, will do.

**Comment by saketkc** [comment]
Thanks @dibyaaaaax!

**Pull request merged**
